package eu.stamp.botsing.controller.event.actions;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class BotsingTestFiles extends  TestFiles {


	private String dataFileString;
	private final String EXTENDS = "\\s+extends\\s+";
	private final String IMPORT_EVOSUITE_REGEX = "import\\s+.+evosuite.+;\\s*";
	private final String EVOSUITE_COMMENT_REGEX = "\\s+generated by EvoSuite\\s*";
	private final String BOTSING_COMMENT = " generated by Botsing\n";
	
	@Override
	public void setDataFile(String fileName,File dataFile) {
		this.dataFileString = null;
		super.setDataFile(fileName,dataFile);
	}

	public String getDataFileString () throws Exception
	{
		File dataFile = getDataFile();
		this.dataFileString = getDataString(dataFile);
		return this.dataFileString;
		
	}
	
	
	
	private String getDataString (File dataFile) throws IOException
	{
		String dataFileString = new String(Files.readAllBytes(Paths.get(dataFile.getAbsolutePath())));
		Matcher importEvoSuiteMatcher = Pattern.compile(IMPORT_EVOSUITE_REGEX).matcher(dataFileString);
		dataFileString = importEvoSuiteMatcher.replaceAll("");
		String extendsScaffoldingFileRegex = EXTENDS+getScaffoldingClassName()+"\\s+";
		Matcher extendsScaffoldingFileNameMatecher = Pattern.compile(extendsScaffoldingFileRegex).matcher(dataFileString);
		dataFileString = extendsScaffoldingFileNameMatecher.replaceFirst(" ");
		Matcher commentMatcher = Pattern.compile(EVOSUITE_COMMENT_REGEX).matcher(dataFileString);
		dataFileString = commentMatcher.replaceAll(BOTSING_COMMENT);
		return dataFileString;
	}
	
	private String getScaffoldingClassName ()
	{
		return getScaffoldingFileName().replace(".java", "");
	}
	

		

}
